### ISSUE TITLE
Как подбирать характеристики под сигнал?

### ISSUE THREAD

**Issue by alex-eri** [GyverLibs/Gyver433#1]
Этот сигнал похож на 433?

![Снимок экрана от 2022-10-19 11-44-02](https://user-images.githubusercontent.com/1091576/196644101-9d11d436-b44d-475e-9322-b26ccb92b61b.png)
![Снимок экрана от 2022-10-19 11-46-10](https://user-images.githubusercontent.com/1091576/196644123-04278f69-898e-44b2-9d83-64039c7529f1.png)

и  ещё пакет

![image](https://user-images.githubusercontent.com/1091576/196652068-1421b38b-d44d-4e07-b063-b2422d04bab5.png)

Ширина импульсов в начале 360=(4520-1635)/8 микросекунд

потом единичка 4780us и ноль 2400 us

ширина посылки 54375

**Comment by GyverLibs** [comment]
433 это частота

**Comment by GyverLibs** [comment]
данная библиотека работает по своему собственному интерфейсу, несовместимому с другими 433 пультами и приёмниками
